export const MODAL_VISIBLE = "MODAL_VISIBLE";
export const PROFILE_INDEX = "PROFILE_PIC_INDEX";
export const DELETE_MATCH = "DELETE_MATCH";
export const ADD_MATCH = "ADD_MATCH";
export const ADD_USER_SUBSCRIPTION = "ADD_USER_SUBSCRIPTION";
export const RESET_SUBSCRIPTIONS = "RESET_SUBSCRIPTIONS";
export const UPDATE_CURRENT_VIEWED_SUBSCRIPTION = "UPDATE_CURRENT_SUBSCRIPTION";
export const SET_LOGIN_TOKEN = "SET_LOGIN_TOKEN";
